### ISSUE TITLE
Update file on disk too, not just in the git index

### ISSUE THREAD

**Issue by rhullah** [miratechcorp/CsProjArrange#5]
I really like this solution you've come up with as I've been looking for a better way to manage merge issues with csproj files.  But one thing I'm not sure how to solve is that setting it up the way you suggest only updates the file in the git index.  It doesn't update the csproj on the filesystem.  Meaning if I edit the csproj it still shows the un-sorted version of the file.

Any suggestions on how to fix this?

**Comment by schmalls** [comment]
Can you see if also specifying a smudge filter helps?

```
[filter "csprojarrange"]
  clean = CsProjArrange
  smudge = CsProjArrange
```

**Comment by schmalls** [comment]
Closing this as I believe the smudge filter will fix the issue.
